### ISSUE TITLE
Řazení faktur podle data

### ISSUE THREAD

**Issue by AloisSeckar** [svobodni/party_payments#2]
ve výpisu faktur je pořadí: "Před 16 dny" - "Před 2 dny" - "Před 22 dny"...z toho mi plyne, že se to řadí podle vypisovaného textu, ne podle samotného data, a je to tudíž přeházené

**Comment by kubicek** [comment]
Třídění podle sloupců je v JS přes Datatables.

Nějak mě nenapadá, jak to udělat lépe. Mohu přidat skrytý sloupeček, a defaultně třídit podle něj, jakmile ale přetřídíš podle jiného, tak se k tomuhle třídění u nevrátíš.

Alternativou by bylo místo hezkého "před 14 dny" dávat datum ve formátu "2015-03-04", podle toho půjde třídit správně, ale zas to bude ošklivé.

**Comment by AloisSeckar** [comment]
v tom případě hlasuju pro "ošklivé"...ale když to chci seřadit podle data (což jsem třeba teď potřeboval, abych viděl jestli Martin už nenahrál fakturu), tak bych rád nejnovější první a ne uprostřed :(
